### ISSUE TITLE
Unable to run！

### ISSUE THREAD

**Issue by zhoushuren** [shadowsocks/shadow-shop#1]
System： Mac OS 10.14
zsh

➜  shadow-shop git:(master) ✗ sudo sh init.sh
Password:
Sorry, try again.
Password:
Please select website stage:
			 d. Development
			 p. Production
d
-e Your choice is: \033[0;32mDevelopment\033[0m
Please input the domain name that you want to use:
testss.com
tr: Illegal byte sequence
chown: www-data: illegal group name
sudo: usermod: command not found
sudo: usermod: command not found
sudo: usermod: command not found
chmod: --recursive: No such file or directory
chmod: /home/jim: No such file or directory
-e \033[0;32mSucess!\033[0m
-e Please restart the server and login as \033[0;32m jim \033[0m

**Comment by Eggham** [comment]
Mac OS and Windows environment are not supported yet.

Please try in a Linux environment...
