### ISSUE TITLE
Can I deploy shadow-shop to an already running woocommerce site?

### ISSUE THREAD

**Issue by 70599** [shadowsocks/shadow-shop#10]

**Comment by Eggham** [comment]
I guess there might be a conflict of ports. Shadow-show requires port 80 and 443 to be available.

If your existing woocommerce site does not use these two ports, then it would be fine to deploy shadow-shop on the same server. Shadow-shop encapsulates the wordpress application using docker containers.

**Comment by 70599** [comment]
Thank you.
- Upload 'shadow-shop/website/wp-content/plugins/shadowsocks-hub' to my existing wordpress plugin path.
- Got following errors at Shadow Shop > Servers page:
    - `Backend system error: Could not resolve host: sshub; Unknown error`
    - `Warning: usort() expects parameter 1 to be array, null given in /path-to-wp/wp-content/plugins/shadowsocks-hub/admin/class-shadowsocks-hub-servers-list-table.php on line 45`
    - `Warning: count(): Parameter must be an array or an object that implements Countable in /path-to-wp/wp-content/plugins/shadowsocks-hub/admin/class-shadowsocks-hub-servers-list-table.php on line 54`
    - `Warning: array_slice() expects parameter 1 to be array, null given in /path-to-wp/wp-content/plugins/shadowsocks-hub/admin/class-shadowsocks-hub-servers-list-table.php on line 59`

I will reply here or open a new issue if got any further information.
