### ISSUE TITLE
Lose Page

### ISSUE THREAD

**Issue by jaybenjaminlee** [shadowsocks/shadow-shop#11]
Lose the pages: Cart, Checkout, My Account

**Comment by jaybenjaminlee** [comment]
- Go to **Dashboard > WooCommerce > Status**
- Click on **Tools** tab from the top left area
- Scroll down to “**Create default WooCommerce pages**”
- Click on **Create Pages**
- After successfully completing the above steps you will see this message “All missing WooCommerce pages successfully installed.”

**Comment by Eggham** [comment]
Sounds the problem is solved?

**Comment by jaybenjaminlee** [comment]
> Sounds the problem is solved?

Yes~~~

**Comment by Eggham** [comment]
Well done
