### ISSUE TITLE
504

### ISSUE THREAD

**Issue by jaybenjaminlee** [shadowsocks/shadow-shop#12]
When I add node, I meet 504 error, and the node page is no longer accessible.

**Comment by Eggham** [comment]
Could you post a screen shot? Is it possible to reproduce the bug?

**Comment by jaybenjaminlee** [comment]
> Could you post a screen shot? Is it possible to reproduce the bug?

When I make my first purchase，the Shadow Shop created account successfully，I can visit the 「Node」page now，thx
