### ISSUE TITLE
mysql

### ISSUE THREAD

**Issue by jaybenjaminlee** [shadowsocks/shadow-shop#13]

**Comment by jaybenjaminlee** [comment]
What is default user and password？

**Comment by jaybenjaminlee** [comment]
I  think it may be root and pwd as the wordpress, but I can't connect , btw  I opened the 3306 port

**Comment by Eggham** [comment]
Did you mean the Admin user for Wordpress? It is the user that you set up during your first visit of the website upon installation. It password for mysql database is randomly generated for the sake of security.

**Comment by jaybenjaminlee** [comment]
> 你的意思是Wordpress的管理员用户？它是您在安装时首次访问网站时设置的用户。为了安全起见，mysql数据库的密码是随机生成的。

Thank you for your explanation

**Comment by Eggham** [comment]
?

**Comment by jaybenjaminlee** [comment]
> ?

Thx
