### ISSUE TITLE
Unfriendly to novice

### ISSUE THREAD

**Issue by picn0113** [shadowsocks/shadow-shop#17]
Many many conflicts with main system(debian9) packages such as nginx, docker-compose and perhaps errors in iptables rules. It only worked for first installation.
Since the first install, I chose development for testing, all worked fine except can't add nodes and the SSL certificate was self signed. Then I installed let's encrypt's certbot to obtain true certificate. It pulled main system's nginx in automatically and worked well for the first time but not with the shadow-shop. So I delete the shadow-shop using rm and reinstall. It comes '502 Bad Gateway'. I think it's valuable to make documentation complete for new comers. For example:
How to add nodes?
What's in the docker and its configuration.
List the standard iptables rules etc.

Firstly let's solve this:
root@open-bump-2:~/shadow-shop# docker-compose up -d
ERROR: Version in "./docker-compose.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a version of "2" (or "2.0") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/

**Comment by Eggham** [comment]
what are the version for `docker` and `docker-compose`?

**Comment by picn0113** [comment]
root@open-bump-2:~/shadow-shop# docker -v
Docker version 18.09.6, build 481bc77

root@open-bump-2:~/shadow-shop# docker-compose -v
docker-compose version 1.8.0, build unknown

**Comment by picn0113** [comment]
if [ "$COMPOSE_VERSION_OK" = "no" ]
    then
        /bin/echo -e "${RED}Your docker-compose version is too low. Please install or update to the latest version.${NC}"
    fi

![image](https://user-images.githubusercontent.com/50651756/57867268-671b0500-7833-11e9-8640-430c73ba8e15.png)

Yeah, I think the script should exit here, and the dark red is hard to notice.

**Comment by picn0113** [comment]
root@open-bump-2:~/shadow-shop# docker-compose up
Creating network "shadow-shop_default" with the default driver
Creating shadow-shop_db_1 ... done
Creating shadow-shop_sshub_1     ... done
Creating shadow-shop_wordpress_1 ... done
Creating shadow-shop_https-portal_1 ... error

ERROR: for shadow-shop_https-portal_1  Cannot start service https-portal: driver failed programming external connectivity on endpoint shadow-shop_https-portal_1 (bbe4a21085106996d98c33ed0a101fea58160ce7803b6c1bd8b067041438db04): Error starting userland proxy: listen tcp 0.0.0.0:443: bind: address already in use

ERROR: for https-portal  Cannot start service https-portal: driver failed programming external connectivity on endpoint shadow-shop_https-portal_1 (bbe4a21085106996d98c33ed0a101fea58160ce7803b6c1bd8b067041438db04): Error starting userland proxy: listen tcp 0.0.0.0:443: bind: address already in use
ERROR: Encountered errors while bringing up the project.

**Comment by Eggham** [comment]
> Yeah, I think the script should exit here, and the dark red is hard to notice.

Well spotted. Thanks.

**Comment by Eggham** [comment]
> ERROR: for shadow-shop_https-portal_1 Cannot start service https-portal: driver failed programming external connectivity on endpoint shadow-shop_https-portal_1 (bbe4a21085106996d98c33ed0a101fea58160ce7803b6c1bd8b067041438db04): Error starting userland proxy: listen tcp 0.0.0.0:443: bind: address already in use
ERROR: for https-portal Cannot start service https-portal: driver failed programming external connectivity on endpoint shadow-shop_https-portal_1 (bbe4a21085106996d98c33ed0a101fea58160ce7803b6c1bd8b067041438db04): Error starting userland proxy: listen tcp 0.0.0.0:443: bind: address already in use
ERROR: Encountered errors while bringing up the project.

The error says that `443` port is in use. Make sure both `80` and `443` are available before running shadow shop.

**Comment by picn0113** [comment]
root@open-bump-2:~/shadow-shop# docker-compose up    
Starting shadow-shop_db_1 ... done
Starting shadow-shop_wordpress_1 ... done
Starting shadow-shop_sshub_1     ... done
Starting shadow-shop_https-portal_1 ... done
Attaching to shadow-shop_db_1, shadow-shop_wordpress_1, shadow-shop_sshub_1, shadow-shop_https-portal_1
wordpress_1     | 
wordpress_1     | Warning: mysqli::__construct(): (HY000/2002): Connection refused in - on line 22
wordpress_1     | 
wordpress_1     | MySQL Connection Error: (2002) Connection refused
https-portal_1  | [fix-attrs.d] applying owners & permissions fixes...
https-portal_1  | [fix-attrs.d] 00-runscripts: applying... 
https-portal_1  | [fix-attrs.d] 00-runscripts: exited 0.
https-portal_1  | [fix-attrs.d] done.
https-portal_1  | [cont-init.d] executing container initialization scripts...
https-portal_1  | [cont-init.d] 00-welcome: executing... 
https-portal_1  | 
https-portal_1  | ========================================
https-portal_1  | HTTPS-PORTAL v1.5.0
https-portal_1  | ========================================
https-portal_1  | 
https-portal_1  | [cont-init.d] 00-welcome: exited 0.
https-portal_1  | [cont-init.d] 10-persist-env: executing... 
https-portal_1  | [cont-init.d] 10-persist-env: exited 0.
https-portal_1  | [cont-init.d] 20-setup: executing... 
db_1            | 2019-05-18T10:12:48.382654Z 0 [Warning] [MY-011070] [Server] 'Disabling symbolic links using --skip-symbolic-links (or equivalent) is the default. Consider not using this option as it' is deprecated and will be removed in a future release.
db_1            | 2019-05-18T10:12:48.382815Z 0 [System] [MY-010116] [Server] /usr/sbin/mysqld (mysqld 8.0.14) starting as process 1
db_1            | 2019-05-18T10:12:52.883245Z 0 [Warning] [MY-010068] [Server] CA certificate ca.pem is self signed.
db_1            | 2019-05-18T10:12:52.926836Z 0 [Warning] [MY-011810] [Server] Insecure configuration for --pid-file: Location '/var/run/mysqld' in the path is accessible to all OS users. Consider choosing a different directory.
db_1            | 2019-05-18T10:12:53.023835Z 0 [System] [MY-010931] [Server] /usr/sbin/mysqld: ready for connections. Version: '8.0.14'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  MySQL Community Server - GPL.
db_1            | 2019-05-18T10:12:53.172568Z 0 [System] [MY-011323] [Server] X Plugin ready for connections. Socket: '/var/run/mysqld/mysqlx.sock' bind-address: '::' port: 33060
https-portal_1  | Error: Invalid descriptor -> http://wordpress
https-portal_1  | /opt/certs_manager/models/domain.rb:72:in `name': undefined method `[]' for nil:NilClass (NoMethodError)
https-portal_1  |       from /opt/certs_manager/models/domain.rb:39:in `dir'
https-portal_1  |       from /opt/certs_manager/models/domain.rb:121:in `create_dir'
https-portal_1  |       from /opt/certs_manager/models/domain.rb:10:in `initialize'
https-portal_1  |       from /opt/certs_manager/lib/na_config.rb:50:in `new'
https-portal_1  |       from /opt/certs_manager/lib/na_config.rb:50:in `block in parse'
https-portal_1  |       from /opt/certs_manager/lib/na_config.rb:49:in `map'
https-portal_1  |       from /opt/certs_manager/lib/na_config.rb:49:in `parse'
https-portal_1  |       from /opt/certs_manager/lib/na_config.rb:32:in `env_domains'
https-portal_1  |       from /opt/certs_manager/lib/na_config.rb:3:in `domains'
https-portal_1  |       from /opt/certs_manager/certs_manager.rb:11:in `setup'
https-portal_1  |       from /etc/cont-init.d/20-setup:4:in `<main>'
https-portal_1  | [cont-init.d] 20-setup: exited 1.
https-portal_1  | [cont-init.d] 30-set-docker-gen-status: executing... 
https-portal_1  | [cont-init.d] 30-set-docker-gen-status: exited 0.
https-portal_1  | [cont-init.d] done.
https-portal_1  | [services.d] starting services
https-portal_1  | [services.d] done.
https-portal_1  | Starting crond ...
wordpress_1     | 
wordpress_1     | Warning: mysqli::__construct(): (HY000/1045): Access denied for user 'root'@'172.18.0.1' (using password: YES) in - on line 22
wordpress_1     | 
wordpress_1     | MySQL Connection Error: (1045) Access denied for user 'root'@'172.18.0.1' (using password: YES)
sshub_1         | knex.migrate.latest() errors
wordpress_1     | 
wordpress_1     | Warning: mysqli::__construct(): (HY000/1045): Access denied for user 'root'@'172.18.0.1' (using password: YES) in - on line 22
wordpress_1     | 
wordpress_1     | MySQL Connection Error: (1045) Access denied for user 'root'@'172.18.0.1' (using password: YES)
wordpress_1     | 
wordpress_1     | Warning: mysqli::__construct(): (HY000/1045): Access denied for user 'root'@'172.18.0.1' (using password: YES) in - on line 22
wordpress_1     | 
wordpress_1     | MySQL Connection Error: (1045) Access denied for user 'root'@'172.18.0.1' (using password: YES)
sshub_1         | knex.migrate.latest() errors
shadow-shop_sshub_1 exited with code 1
wordpress_1     | 
wordpress_1     | Warning: mysqli::__construct(): (HY000/1045): Access denied for user 'root'@'172.18.0.1' (using password: YES) in - on line 22
wordpress_1     | 
wordpress_1     | MySQL Connection Error: (1045) Access denied for user 'root'@'172.18.0.1' (using password: YES)
wordpress_1     | 
wordpress_1     | Warning: mysqli::__construct(): (HY000/1045): Access denied for user 'root'@'172.18.0.1' (using password: YES) in - on line 22
wordpress_1     | 
wordpress_1     | MySQL Connection Error: (1045) Access denied for user 'root'@'172.18.0.1' (using password: YES)
sshub_1         | knex.migrate.latest() errors
shadow-shop_sshub_1 exited with code 1
wordpress_1     | 
wordpress_1     | Warning: mysqli::__construct(): (HY000/1045): Access denied for user 'root'@'172.18.0.1' (using password: YES) in - on line 22
wordpress_1     | 
wordpress_1     | MySQL Connection Error: (1045) Access denied for user 'root'@'172.18.0.1' (using password: YES)
wordpress_1     | 
wordpress_1     | MySQL Connection Error: (1045) Access denied for user 'root'@'172.18.0.1' (using password: YES)
wordpress_1     | 
wordpress_1     | Warning: mysqli::__construct(): (HY000/1045): Access denied for user 'root'@'172.18.0.1' (using password: YES) in - on line 22
sshub_1         | knex.migrate.latest() errors
shadow-shop_sshub_1 exited with code 1
wordpress_1     | 
wordpress_1     | Warning: mysqli::__construct(): (HY000/1045): Access denied for user 'root'@'172.18.0.1' (using password: YES) in - on line 22
wordpress_1     | 
wordpress_1     | MySQL Connection Error: (1045) Access denied for user 'root'@'172.18.0.1' (using password: YES)
wordpress_1     | 
wordpress_1     | Warning: mysqli::__construct(): (HY000/1045): Access denied for user 'root'@'172.18.0.1' (using password: YES) in - on line 22
wordpress_1     | 
wordpress_1     | MySQL Connection Error: (1045) Access denied for user 'root'@'172.18.0.1' (using password: YES)
sshub_1         | knex.migrate.latest() errors
shadow-shop_sshub_1 exited with code 1
wordpress_1     | 
wordpress_1     | Warning: mysqli::__construct(): (HY000/1045): Access denied for user 'root'@'172.18.0.1' (using password: YES) in - on line 22
wordpress_1     | 
wordpress_1     | MySQL Connection Error: (1045) Access denied for user 'root'@'172.18.0.1' (using password: YES)
wordpress_1     | 
wordpress_1     | Warning: mysqli::__construct(): (HY000/1045): Access denied for user 'root'@'172.18.0.1' (using password: YES) in - on line 22
wordpress_1     | 
wordpress_1     | MySQL Connection Error: (1045) Access denied for user 'root'@'172.18.0.1' (using password: YES)
sshub_1         | knex.migrate.latest() errors
shadow-shop_sshub_1 exited with code 1
wordpress_1     | 
wordpress_1     | Warning: mysqli::__construct(): (HY000/1045): Access denied for user 'root'@'172.18.0.1' (using password: YES) in - on line 22
wordpress_1     | 
wordpress_1     | MySQL Connection Error: (1045) Access denied for user 'root'@'172.18.0.1' (using password: YES)
wordpress_1     | 
wordpress_1     | Warning: mysqli::__construct(): (HY000/1045): Access denied for user 'root'@'172.18.0.1' (using password: YES) in - on line 22
wordpress_1     | 
wordpress_1     | MySQL Connection Error: (1045) Access denied for user 'root'@'172.18.0.1' (using password: YES)
wordpress_1     | 
wordpress_1     | MySQL Connection Error: (1045) Access denied for user 'root'@'172.18.0.1' (using password: YES)
wordpress_1     | 
wordpress_1     | Warning: mysqli::__construct(): (HY000/1045): Access denied for user 'root'@'172.18.0.1' (using password: YES) in - on line 22
sshub_1         | knex.migrate.latest() errors
shadow-shop_sshub_1 exited with code 1
wordpress_1     | 
wordpress_1     | Warning: mysqli::__construct(): (HY000/1045): Access denied for user 'root'@'172.18.0.1' (using password: YES) in - on line 22
wordpress_1     | 
wordpress_1     | MySQL Connection Error: (1045) Access denied for user 'root'@'172.18.0.1' (using password: YES)
wordpress_1     | 
wordpress_1     | Warning: mysqli::__construct(): (HY000/1045): Access denied for user 'root'@'172.18.0.1' (using password: YES) in - on line 22
wordpress_1     | 
wordpress_1     | MySQL Connection Error: (1045) Access denied for user 'root'@'172.18.0.1' (using password: YES)
wordpress_1     | 
wordpress_1     | Warning: mysqli::__construct(): (HY000/1045): Access denied for user 'root'@'172.18.0.1' (using password: YES) in - on line 22
wordpress_1     | 
wordpress_1     | MySQL Connection Error: (1045) Access denied for user 'root'@'172.18.0.1' (using password: YES)
sshub_1         | knex.migrate.latest() errors
shadow-shop_sshub_1 exited with code 1
wordpress_1     | 
wordpress_1     | MySQL Connection Error: (1045) Access denied for user 'root'@'172.18.0.1' (using password: YES)
wordpress_1     | 
wordpress_1     | Warning: mysqli::__construct(): (HY000/1045): Access denied for user 'root'@'172.18.0.1' (using password: YES) in - on line 22
wordpress_1     | 
wordpress_1     | Warning: mysqli::__construct(): (HY000/1045): Access denied for user 'root'@'172.18.0.1' (using password: YES) in - on line 22
wordpress_1     | 
wordpress_1     | MySQL Connection Error: (1045) Access denied for user 'root'@'172.18.0.1' (using password: YES)
shadow-shop_wordpress_1 exited with code 0
wordpress_1     | 
wordpress_1     | Warning: mysqli::__construct(): (HY000/1045): Access denied for user 'root'@'172.18.0.1' (using password: YES) in - on line 22
wordpress_1     | 
wordpress_1     | MySQL Connection Error: (1045) Access denied for user 'root'@'172.18.0.1' (using password: YES)
wordpress_1     | 
wordpress_1     | Warning: mysqli::__construct(): (HY000/1045): Access denied for user 'root'@'172.18.0.1' (using password: YES) in - on line 22
wordpress_1     | 
wordpress_1     | MySQL Connection Error: (1045) Access denied for user 'root'@'172.18.0.1' (using password: YES)
wordpress_1     | 
wordpress_1     | Warning: mysqli::__construct(): (HY000/1045): Access denied for user 'root'@'172.18.0.1' (using password: YES) in - on line 22
wordpress_1     | 
wordpress_1     | MySQL Connection Error: (1045) Access denied for user 'root'@'172.18.0.1' (using password: YES)
wordpress_1     | 
wordpress_1     | Warning: mysqli::__construct(): (HY000/1045): Access denied for user 'root'@'172.18.0.1' (using password: YES) in - on line 22
wordpress_1     | 
wordpress_1     | MySQL Connection Error: (1045) Access denied for user 'root'@'172.18.0.1' (using password: YES)
wordpress_1     | 
wordpress_1     | Warning: mysqli::__construct(): (HY000/1045): Access denied for user 'root'@'172.18.0.1' (using password: YES) in - on line 22
wordpress_1     | 
wordpress_1     | MySQL Connection Error: (1045) Access denied for user 'root'@'172.18.0.1' (using password: YES)
sshub_1         | knex.migrate.latest() errors
shadow-shop_sshub_1 exited with code 1
wordpress_1     | 
wordpress_1     | Warning: mysqli::__construct(): (HY000/1045): Access denied for user 'root'@'172.18.0.1' (using password: YES) in - on line 22
wordpress_1     | 
wordpress_1     | MySQL Connection Error: (1045) Access denied for user 'root'@'172.18.0.1' (using password: YES)
wordpress_1     | 
wordpress_1     | Warning: mysqli::__construct(): (HY000/1045): Access denied for user 'root'@'172.18.0.1' (using password: YES) in - on line 22
wordpress_1     | 
wordpress_1     | MySQL Connection Error: (1045) Access denied for user 'root'@'172.18.0.1' (using password: YES)

and more...

**Comment by Eggham** [comment]
There are something wrong with starting shadow show. Can you show the output of status of docker containers as follows:
```
cd ~/shadow-shop
docker-compose ps
```

**Comment by picn0113** [comment]
![image](https://user-images.githubusercontent.com/50651756/57968563-d2cdb100-799e-11e9-8c58-12c0795e9ec0.png)

**Comment by Eggham** [comment]
It seems that docker containers was not running. But once you ran `docker-compose up -d`, all containers are running fine. You should now be able to use shadow shop. Are you still encountering any problem?

**Comment by picn0113** [comment]
Of course no. It's only the surface.

**Comment by picn0113** [comment]
Why mysql access denied?

**Comment by Eggham** [comment]
If you are able to use shadow shop without problems, then wordpress container is accessing mysql container without a problem. I guess the problem was because mysql container was down...

**Comment by picn0113** [comment]
But cannot use.

**Comment by Eggham** [comment]
Can you show the output of `.env` file?
```
cd ~/shadow-shop
cat .env
```

**Comment by picn0113** [comment]
root@open-bump-2:~/shadow-shop# cat .env
DOMAIN_NAME=
STAGE=production
MYSQL_PASSWORD=WzJu0EGZnfCuWr3FSdN0oESagT06b4y8

**Comment by Eggham** [comment]
Did you modify `.env` file? `DOMAIN_NAME=` should be followed by the domain name you chose. It is empty now, which would lead to errors.

**Comment by Eggham** [comment]
You could re-run the following commands to fix it. Note you need a valid domain name. You may choose `Development` mode first to play with shadow shop. Once you are ready for production, then re-run `sudo sh init.sh` and choose `Production` mode.
```
cd ~/shadow-shop
sudo sh init.sh
```

Then re-create the docker containers as follows:
```
cd ~/shadow-shop
docker-compose down -v
docker-compose up -d
```
Note that `docker-compose down -v` will delete all database from previous containers.

**Comment by picn0113** [comment]
Yep, it's OK. Thank you very much.

**Comment by picn0113** [comment]
After install, it's a blank.
![image](https://user-images.githubusercontent.com/50651756/57979040-4f699980-7a4a-11e9-9cd6-f3ca450e1826.png)

**Comment by picn0113** [comment]
![image](https://user-images.githubusercontent.com/50651756/57979154-1a5e4680-7a4c-11e9-97d6-8878dd91d4d3.png)

**Comment by Eggham** [comment]
It seems your shadow shop version contains some error. Shadow shop should update itself automatically. Can you show output of the following command:
```
crontab -l
```
I suggest you manually update shadow shop to the latest version first and try again:
```
cd ~/shadow-shop
docker-compose down -v
git pull origin master
sudo sh init.sh
docker-compose up -d
```
If it still does not work, could you please show the output of showing docker container status:
```
cd ~/shadow-shop
docker-compose ps
```

**Comment by picn0113** [comment]
root@open-bump-2:~/shadow-shop# crontab -l
7 19 * * * sh /root/shadow-shop/update.sh /root/shadow-shop /usr/bin/docker-compose

**Comment by picn0113** [comment]
root@open-bump-2:~/shadow-shop# git pull origin master
remote: Enumerating objects: 959, done.
remote: Counting objects: 100% (959/959), done.
remote: Compressing objects: 100% (219/219), done.
remote: Total 727 (delta 557), reused 658 (delta 507), pack-reused 0
Receiving objects: 100% (727/727), 1.79 MiB | 0 bytes/s, done.
Resolving deltas: 100% (557/557), completed with 226 local objects.
From https://github.com/shadowsocks/shadow-shop
 * branch            master     -> FETCH_HEAD
   f4af10d..d9b61ce  master     -> origin/master
Updating f4af10d..d9b61ce
error: Your local changes to the following files would be overwritten by merge:
        website/wp-content/languages/admin-de_DE.mo
        website/wp-content/languages/admin-de_DE.po
        website/wp-content/languages/admin-en_GB.mo
        website/wp-content/languages/admin-en_GB.po
        website/wp-content/languages/admin-es_ES.mo
        website/wp-content/languages/admin-es_ES.po
        website/wp-content/languages/admin-fr_FR.mo
        website/wp-content/languages/admin-fr_FR.po
        website/wp-content/languages/admin-it_IT.mo
        website/wp-content/languages/admin-it_IT.po
        website/wp-content/languages/admin-ja.mo
        website/wp-content/languages/admin-ja.po
        website/wp-content/languages/admin-network-en_GB.mo
        website/wp-content/languages/admin-network-en_GB.po
        website/wp-content/languages/admin-network-fr_FR.mo
        website/wp-content/languages/admin-network-fr_FR.po
        website/wp-content/languages/admin-ru_RU.mo
        website/wp-content/languages/admin-ru_RU.po
        website/wp-content/languages/admin-vi.mo
        website/wp-content/languages/admin-vi.po
        website/wp-content/languages/de_DE-0ce75ad2f775d1cac9696967d484808c.json
        website/wp-content/languages/de_DE-1a0cd6a7128913b15c1a10dd68951869.json
        website/wp-content/languages/de_DE-1bba9045bb07c89671c88a3f328548e8.json
        website/wp-content/languages/de_DE-28b3c3d595952907e08d98287077426c.json
        website/wp-content/languages/de_DE-2c5d274ea625dd91556554ad82901529.json
        website/wp-content/languages/de_DE-4a38fe1c0c45989e44682ba6109d9f46.json
        website/wp-content/languages/de_DE-68f2cec7514bf8563c723a4d675fcfe6.json
        website/wp-content/languages/de_DE-7f13c36c641b114bf18cd0bcc9ecc7e0.json
        website/wp-content/languages/de_DE-803bf1ce2131e13efc590c1bc47851fc.json
        website/wp-content/languages/de_DE-8860e58c20c6a2ab5876a0f07be43bd9.json
        website/wp-content/languages/de_DE-a25d1cc7bf7ca0b4e114f6bea64943f4.json
        website/wp-content/languages/de_DE-bf0f094965d3d4a95b47babcb35fc136.json
        website/wp-content/languages/de_DE-f8f49d9fc4a9cf7d78ec99285417bd9c.json
        website/wp-content/languages/de_DE.mo
        website/wp-content/languages/de_DE.po
        website/wp-content/languages/en_GB-0ce75ad2f775d1cac9696967d484808c.json
        website/wp-content/languages/en_GB-1a0cd6a7128913b15c1a10dd68951869.json
        website/wp-content/languages/en_GB-1bba9045bb07c89671c88a3f328548e8.json
        website/wp-content/languages/en_GB-28b3c3d595952907e08d98287077426c.json
        website/wp-content/languages/en_GB-2c5d274ea625dd91556554ad82901529.json
        website/wp-content/languages/en_GB-4a38fe1c0c45989e44682ba6109d9f46.json
        website/wp-content/languages/en_GB-68f2cec7514bf8563c723a4d675fcfe6.json
        website/wp-content/languages/en_GB-7f13c36c641b114bf18cd0bcc9ecc7e0.json
        website/wp-content/languages/en_GB-803bf1ce2131e13efc590c1bc47851fc.json
        website/wp-content/languages/en_GB-8860e58c20c6a2ab5876a0f07be43bd9.json
        website/wp-content/languages/en_GB-a25d1cc7bf7ca0b4e114f6bea64943f4.json
        website/wp-content/languages/en_GB-bf0f094965d3d4a95b47babcb35fc136.json
        website/wp-content/languages/en_GB-f8f49d9fc4a9cf7d78ec99285417bd9c.json
        website/wp-content/languages/en_GB.mo
        website/wp-content/languages/en_GB.po
        website/wp-content/languages/es_ES-0ce75ad2f775d1cac9696967d484808c.json
        website/wp-content/languages/es_ES-1a0cd6a7128913b15c1a10dd68951869.json
        website/wp-content/languages/es_ES-1bba9045bb07c89671c88a3f328548e8.json
        website/wp-content/languages/es_ES-28b3c3d595952907e08d98287077426c.json
        website/wp-content/languages/es_ES-2c5d274ea625dd91556554ad82901529.json
        website/wp-content/languages/es_ES-4a38fe1c0c45989e44682ba6109d9f46.json
        website/wp-content/languages/es_ES-68f2cec7514bf8563c723a4d675fcfe6.json
        website/wp-content/languages/es_ES-7f13c36c641b114bf18cd0bcc9ecc7e0.json
        website/wp-content/languages/es_ES-803bf1ce2131e13efc590c1bc47851fc.json
        website/wp-content/languages/es_ES-8860e58c20c6a2ab5876a0f07be43bd9.json
        website/wp-content/languages/es_ES-a25d1cc7bf7ca0b4e114f6bea64943f4.json
        website/wp-content/languages/es_ES-bf0f094965d3d4a95b47babcb35fc136.json
        website/wp-content/languages/es_ES-f8f49d9fc4a9cf7d78ec99285417bd9c.json
        website/wp-content/languages/es_ES.mo
        website/wp-content/languages/es_ES.po
        website/wp-content/languages/fr_FR-0ce75ad2f775d1cac9696967d484808c.json
        website/wp-content/languages/fr_FR-1a0cd6a7128913b15c1a10dd68951869.json
        website/wp-content/languages/fr_FR-1bba9045bb07c89671c88a3f328548e8.json
        website/wp-content/languages/fr_FR-28b3c3d595952907e08d98287077426c.json
        website/wp-content/languages/fr_FR-2c5d274ea625dd91556554ad82901529.json
        website/wp-content/languages/fr_FR-4a38fe1c0c45989e44682ba6109d9f46.json
        website/wp-content/languages/fr_FR-68f2cec7514bf8563c723a4d675fcfe6.json
        website/wp-content/languages/fr_FR-7f13c36c641b114bf18cd0bcc9ecc7e0.json
        website/wp-content/languages/fr_FR-803bf1ce2131e13efc590c1bc47851fc.json
        website/wp-content/languages/fr_FR-8860e58c20c6a2ab5876a0f07be43bd9.json
        website/wp-content/languages/fr_FR-a25d1cc7bf7ca0b4e114f6bea64943f4.json
        website/wp-content/languages/fr_FR-bf0f094965d3d4a95b47babcb35fc136.json
        website/wp-content/languages/fr_FR-f8f49d9fc4a9cf7d78ec99285417bd9c.json
        website/wp-content/languages/fr_FR.mo
        website/wp-content/languages/fr_FR.po
        website/wp-content/languages/it_IT-0ce75ad2f775d1cac9696967d484808c.json
        website/wp-content/languages/it_IT-1a0cd6a7128913b15c1a10dd68951869.json
        website/wp-content/languages/it_IT-1bba9045bb07c89671c88a3f328548e8.json
        website/wp-content/languages/it_IT-28b3c3d595952907e08d98287077426c.json
        website/wp-content/languages/it_IT-2c5d274ea625dd91556554ad82901529.json
        website/wp-content/languages/it_IT-4a38fe1c0c45989e44682ba6109d9f46.json
        website/wp-content/languages/it_IT-68f2cec7514bf8563c723a4d675fcfe6.json
        website/wp-content/languages/it_IT-7f13c36c641b114bf18cd0bcc9ecc7e0.json
        website/wp-content/languages/it_IT-803bf1ce2131e13efc590c1bc47851fc.json
        website/wp-content/languages/it_IT-8860e58c20c6a2ab5876a0f07be43bd9.json
        website/wp-content/languages/it_IT-a25d1cc7bf7ca0b4e114f6bea64943f4.json
        website/wp-content/languages/it_IT-bf0f094965d3d4a95b47babcb35fc136.json
        website/wp-content/languages/it_IT-f8f49d9fc4a9cf7d78ec99285417bd9c.json
        website/wp-content/languages/it_IT.mo
        website/wp-content/languages/it_IT.po
        website/wp-content/languages/ja-0ce75ad2f775d1cac9696967d484808c.json
        website/wp-content/languages/ja-1a0cd6a7128913b15c1a10dd68951869.json
        website/wp-content/languages/ja-1bba9045bb07c89671c88a3f328548e8.json
        website/wp-content/languages/ja-28b3c3d595952907e08d98287077426c.json
        website/wp-content/languages/ja-2c5d274ea625dd91556554ad82901529.json
        website/wp-content/languages/ja-4a38fe1c0c45989e44682ba6109d9f46.json
        website/wp-content/languages/ja-68f2cec7514bf8563c723a4d675fcfe6.json
        website/wp-content/languages/ja-7f13c36c641b114bf18cd0bcc9ecc7e0.json
        website/wp-content/languages/ja-803bf1ce2131e13efc590c1bc47851fc.json
        website/wp-content/languages/ja-8860e58c20c6a2ab5876a0f07be43bd9.json
        website/wp-content/languages/ja-a25d1cc7bf7ca0b4e114f6bea64943f4.json
        website/wp-content/languages/ja-bf0f094965d3d4a95b47babcb35fc136.json
        website/wp-content/languages/ja-f8f49d9fc4a9cf7d78ec99285417bd9c.json
        website/wp-content/languages/ja.mo
        website/wp-content/languages/ja.po
        website/wp-content/languages/plugins/woocommerce-en_GB.mo
        website/wp-content/languages/plugins/woocommerce-en_GB.po
        website/wp-content/languages/plugins/woocommerce-es_ES.mo
        website/wp-content/languages/plugins/woocommerce-es_ES.po
        website/wp-content/languages/ru_RU-0ce75ad2f775d1cac9696967d484808c.json
        website/wp-content/languages/ru_RU-1a0cd6a7128913b15c1a10dd68951869.json
        website/wp-content/languages/ru_RU-1bba9045bb07c89671c88a3f328548e8.json
        website/wp-content/languages/ru_RU-28b3c3d595952907e08d98287077426c.json
        website/wp-content/languages/ru_RU-2c5d274ea625dd91556554ad82901529.json
        website/wp-content/languages/ru_RU-4a38fe1c0c45989e44682ba6109d9f46.json
        website/wp-content/languages/ru_RU-68f2cec7514bf8563c723a4d675fcfe6.json
        website/wp-content/languages/ru_RU-7f13c36c641b114bf18cd0bcc9ecc7e0.json
        website/wp-content/languages/ru_RU-803bf1ce2131e13efc590c1bc47851fc.json
        website/wp-content/languages/ru_RU-8860e58c20c6a2ab5876a0f07be43bd9.json
        website/wp-content/languages/ru_RU-a25d1cc7bf7ca0b4e114f6bea64943f4.json
        website/wp-content/languages/ru_RU-bf0f094965d3d4a95b47babcb35fc136.json
        website/wp-content/languages/ru_RU-f8f49d9fc4a9cf7d78ec99285417bd9c.json
        website/wp-content/languages/ru_RU.mo
        website/wp-content/languages/ru_RU.po
        website/wp-content/languages/themes/storefront-de_DE.mo
        website/wp-content/languages/themes/storefront-de_DE.po
        website/wp-content/languages/vi-0ce75ad2f775d1cac9696967d484808c.json
        website/wp-content/languages/vi-1a0cd6a7128913b15c1a10dd68951869.json
        website/wp-content/languages/vi-1bba9045bb07c89671c88a3f328548e8.json
        website/wp-content/languages/vi-28b3c3d595952907e08d98287077426c.json
        website/wp-content/languages/vi-2c5d274ea625dd91556554ad82901529.json
        website/wp-content/languages/vi-4a38fe1c0c45989e44682ba6109d9f46.json
        website/wp-content/languages/vi-68f2cec7514bf8563c723a4d675fcfe6.json
        website/wp-content/languages/vi-7f13c36c641b114bf18cd0bcc9ecc7e0.json
        website/wp-content/languages/vi-803bf1ce2131e13efc590c1bc47851fc.json
        website/wp-content/languages/vi-8860e58c20c6a2ab5876a0f07be43bd9.json
        website/wp-content/languages/vi-a25d1cc7bf7ca0b4e114f6bea64943f4.json
        website/wp-content/languages/vi-bf0f094965d3d4a95b47babcb35fc136.json
        website/wp-content/languages/vi-f8f49d9fc4a9cf7d78ec99285417bd9c.json
        website/wp-content/languages/vi.mo
        website/wp-content/languages/vi.po
Please commit your changes or stash them before you merge.
Aborting

I think I should rm ~/shadow-shop first?

**Comment by Eggham** [comment]
You could do a fresh install as follows:
```
cd ~/shadow-shop
docker-compose down -v
cd ~
rm shadow-shop -rf
git clone https://github.com/shadowsocks/shadow-shop.git
cd ~/shadow-shop
sudo sh init.sh
docker-compose up -d
```

**Comment by picn0113** [comment]
![image](https://user-images.githubusercontent.com/50651756/57982666-0b42bd00-7a7b-11e9-9268-091ea44a1772.png)
![image](https://user-images.githubusercontent.com/50651756/57982686-43e29680-7a7b-11e9-9fb1-7e7a3de14028.png)

**Comment by picn0113** [comment]
It's up now, thank you.

**Comment by Eggham** [comment]
Is it working now? Just curious what did you do that solved the problem?

**Comment by picn0113** [comment]
> Is it working now? Just curious what did you do that solved the problem?

Nothing. I don't know why mysqlserver temporarily down, maybe out of memory.

**Comment by picn0113** [comment]
Finally, how to add nodes?
![image](https://user-images.githubusercontent.com/50651756/57993810-1fbf9d80-7aed-11e9-8ae0-e1a65d994d8f.png)

**Comment by picn0113** [comment]
It's OK now. It seems 'Lower Bound' should be greater than 'Port'.

**Comment by Eggham** [comment]
Yes. `Port` has to be outside of the range between `Lower Bound` and `Upper Bound`. Usually, `Port` is smaller than `Lower Bound`.
