### ISSUE TITLE
l can‘t install shaow-shop  

### ISSUE THREAD

**Issue by jimmyalxe** [shadowsocks/shadow-shop#18]
MY system ： CentOS  7.4.6 x64 1cpu 1Gb
sudo sh init.sh
Please select website stage: (your last choice was \033[0;32mProduction\033[0m)
\t\t\t d. Development
\t\t\t p. Production
p
You choice is: Production
Please input the domain name that you want to use: (your last input was \033[0;32mss.jimmyalxe.com\033[0m)
ss.jimmyalxe.com
chown: invalid user: ‘www-data:www-data’
usermod: group 'www-data' does not exist
usermod: user 'www-data' does not exist
Sucess!
Please restart the server and login as  root

**Comment by jimmyalxe** [comment]
l'm root

**Comment by Eggham** [comment]
It looks the installation was successful.

What is the output of the following commands?
```
cd ~/shadow-shop
docker-compose ps
```

**Comment by jimmyalxe** [comment]
i try  Is it installed?
Output result
[root@VM_0_10_centos ~]# cd ~/shadow-shop
[root@VM_0_10_centos shadow-shop]# docker-compose ps         
   Name   Command   State   Ports
------------------------------

**Comment by Eggham** [comment]
It seems your containers are not up running. Did you run the following commands before:
```
cd ~/shadow-shop
docker-compose up -d
```

**Comment by jimmyalxe** [comment]
no
l only  run
`cd ~
git clone https://github.com/shadowsocks/shadow-shop.git
cd ~/shadow-shop
sudo sh init.sh`
but docker is install  longtime ago

**Comment by jimmyalxe** [comment]
i run
 `cd ~/shadow-shop
docker-compose up -d`
Output result
`Creating shadow-shop_db_1 ... done
Creating shadow-shop_sshub_1     ... done
Creating shadow-shop_wordpress_1 ... done
Creating shadow-shop_https-portal_1 ... error

ERROR: for shadow-shop_https-portal_1  Cannot start service https-portal: driver failed programming external connectivity on endpoint shadow-shop_https-portal_1 (c415245184d99ec8ee2493f8351982cc0b37da93f51bd1db5ecfda8684cb86b0): Error starting userland proxy: listen tcp 0.0.0.0:80: bind: address already in use

ERROR: for https-portal  Cannot start service https-portal: driver failed programming external connectivity on endpoint shadow-shop_https-portal_1 (c415245184d99ec8ee2493f8351982cc0b37da93f51bd1db5ecfda8684cb86b0): Error starting userland proxy: listen tcp 0.0.0.0:80: bind: address already in use
ERROR: Encountered errors while bringing up the project.
`

**Comment by jimmyalxe** [comment]
this project must instilled on a clean vps？ 
my vps instll bt panel    teddysun‘ss-libev 
Is it because of this reason?

**Comment by Eggham** [comment]
It says that your port `80` is in use. Shadow Shop need both port `80` and `443` are available.

**Comment by jimmyalxe** [comment]
l find 
`netstat -tnlp | grep :80`
`tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      4298/nginx: master`

bt panel install nginx  

hao can i change teh port of shadow shop ? in docker?

**Comment by Eggham** [comment]
No, you can't. Shadow Shop doesn't support changing the port numbers.

**Comment by jimmyalxe** [comment]
ok  mybe i need change a clan vps 
thank for you
