### ISSUE TITLE
I can't access the website

### ISSUE THREAD

**Issue by elatedeer** [shadowsocks/shadow-shop#2]
I started the service successfully, but I was prompted to deny access when I opened the website.
I am sure my domain name resolution is successful.
server : centos7 x64
Startup result: root@vultr shadow-shop]# docker-compose ps
           Name                         Command               State                   Ports                
-----------------------------------------------------------------------------------------------------------
shadow-shop_db_1             docker-entrypoint.sh --def ...   Up      3306/tcp, 33060/tcp                  
shadow-shop_https-portal_1   /init                            Up      0.0.0.0:443->443/tcp,                
                                                                      0.0.0.0:80->80/tcp                   
shadow-shop_sshub_1          /nodejs/bin/node api.js          Up      80/tcp                               
shadow-shop_wordpress_1      docker-entrypoint.sh apach ...   Up      80/tcp     

Can you give me some advice?

**Comment by Eggham** [comment]
What do you mean by you were "prompted to deny access"? Could you please post a screenshot?

From `docker-compose ps` command, it looks that everything is up running well.

**Comment by elatedeer** [comment]
I am very sorry, I forgot to turn off the firewall.
Wasting your time, sorry.

**Comment by Eggham** [comment]
No worries, mate! Glad you figured it out yourself. Perhaps I need remind the users about it as well
