### ISSUE TITLE
setup hava some problem

### ISSUE THREAD

**Issue by zouzhe1** [shadowsocks/shadow-shop#3]
1，domain how input？can do it like bbb.xxxx.com?it show me  error,but ask me y continue......
2, the docker is where local?if i want to remove the  shadow-shop,what i do?
3,the init.sh   can    auto  download  the wordpress code ?

i am chinese,so my english is not good...

**Comment by zouzhe1** [comment]
Couldn't connect to Docker daemon at http+docker://localhost - is it running?

**Comment by Eggham** [comment]
Hi,

Domain name should NOT contain question mark (?). For example, www.mydomain.com is a valid domain name.

You just delete the shadow-shop directory if you want to remove it.

You run your website by type in browser your domain name.

If you like, you may post your screen shot.
