### ISSUE TITLE
I can't configure the connection between shadowsocks-restful-api and shadow-shop

### ISSUE THREAD

**Issue by B451YbUz75Rn** [shadowsocks/shadow-shop#4]
Sorry, I can't configure shadowsocks-restful-api to connect with shadow-shop, and it's hard to find similar tutorials and methods. Does any other friend know?

I can't configure
Shadow-shop server domain name: bbvpn.xyz
Shadowsocks-restful-api nodes domain name: nodes.bbvpn.xyz

Thank you for your help!
![1](https://user-images.githubusercontent.com/38288955/55126789-13e8d800-5149-11e9-9a77-d36a7898f975.png)
![2](https://user-images.githubusercontent.com/38288955/55126790-14816e80-5149-11e9-99b0-2d2ed5d157a0.png)
![3](https://user-images.githubusercontent.com/38288955/55126792-14816e80-5149-11e9-9d5e-7b6846f08099.png)

**Comment by Eggham** [comment]
Port should NOT be between Lower Bound and Upper Bound. You may choose a higher Lower Bound, e.g. 10000.

**Comment by Eggham** [comment]
You should change the default password for at shadowsocks-restful-api and here for security reason.

**Comment by B451YbUz75Rn** [comment]
> 您应该更改shadowocks-restful-api的默认密码，并在此处出于安全原因。

请问我的操作有错误的地方吗？
