### ISSUE TITLE
Follow the instructions to install, the website can not be opened, the firewall is closed!

### ISSUE THREAD

**Issue by B451YbUz75Rn** [shadowsocks/shadow-shop#5]
![图像 2](https://user-images.githubusercontent.com/38288955/55278442-43653380-5347-11e9-9761-106553fb37b7.png)

Wait 15-20 minutes and restart the server.

![图像 6](https://user-images.githubusercontent.com/38288955/55278448-61329880-5347-11e9-825e-7210eb1924b8.png)

**Comment by B451YbUz75Rn** [comment]
I am really sorry for the trouble you have, and I can't solve this problem many times.
System environment ubuntu: 16.04

**Comment by B451YbUz75Rn** [comment]
The website still can't be opened.

**Comment by Eggham** [comment]
what is the output for command `docker-compose ps`?

**Comment by B451YbUz75Rn** [comment]
> what is the output for command `docker-compose ps`?

![QQ截图20190402001700](https://user-images.githubusercontent.com/38288955/55343129-09c63100-54dd-11e9-97ea-06a1b25e0fe1.jpg)

**Comment by Eggham** [comment]
Sorry for not seeing your screen shots at the beginning - it didn't show up.

I suggest you check your iptables using `sudo iptables -L`. `ufw` and `iptables` commands are different things. You may want to google them up...

If you like you may post the output of `sudo iptables -L` command

**Comment by B451YbUz75Rn** [comment]
![01](https://user-images.githubusercontent.com/38288955/55374335-ae2a9080-553a-11e9-8fab-b33c0a201a47.png)

**Comment by Eggham** [comment]
The `443` port of your server is blocked. I ran `nc -zv bbvpn.xyz 443` command from my ubuntu machine, the output showed:
```
nc: connect to bbvpn.xyz port 443 (tcp) failed: Connection refused
```

This is very likely to be the cause of problem.

You need make sure both `80` and `443` ports not blocked.

**Comment by B451YbUz75Rn** [comment]
Thank you very much for your help!
I reloaded the system, changed the domain name, each domain name can only obtain SSL certificate within one weeks is a limited number of times
The reference https://www.digitalocean.com/community/tutorials/how-to-set-up-a-firewall-with-ufw-on-ubuntu-16-04 has been successfully installed. Here are my installation steps to help my friends later.
![install](https://user-images.githubusercontent.com/38288955/55414514-d697a680-559d-11e9-9c81-bea6ac7e3515.png)

**Comment by Eggham** [comment]
Some tips:
1. You can run `sudo sh init.sh` multiple times. You don't have to clone source code more than once.
2. You may choose `Development` mode for debugging or development purposes, avoiding rate limit on obtaining SSL certificates.

Question: Has your problem been solved?

**Comment by B451YbUz75Rn** [comment]
My problem has been solved, thank you for your patient help!

**Comment by Eggham** [comment]
no worries
