### ISSUE TITLE
Shadowsocks-restful-api still fails online, offline!

### ISSUE THREAD

**Issue by B451YbUz75Rn** [shadowsocks/shadow-shop#6]
Shadowsocks-restful-api still fails online, offline!
After the successful construction, I will record a video on the youtube channel for more friends who need it.

installation steps
There are many pictures

![install0](https://user-images.githubusercontent.com/38288955/55496354-6e19f980-5671-11e9-8f0b-b36fe1c7f70e.png)

![install1](https://user-images.githubusercontent.com/38288955/55495806-4ece9c80-5670-11e9-9bf8-2aba6223d5ba.png)

![install2](https://user-images.githubusercontent.com/38288955/55495814-52faba00-5670-11e9-9725-7ade8fc96a5c.png)

![install3](https://user-images.githubusercontent.com/38288955/55495833-5726d780-5670-11e9-9deb-d78f51d83e94.png)
--------------------------------------------------------
shadowsocks-restful-api
I have reinstalled the system because I can't connect.
Server IP: 208.167.245.77
User: root
Password: j1Q@]u{6tmpgt2H@
--------------------------------------------------------
Front-end server  shadow-shop
https://shadowsocks-ss.xyz/wp-login.php
User: administrator
Password: 888996Bb

**Comment by Eggham** [comment]
Thanks for your effort to present these nicely arranged screen shots. I have installed shadowsocks-restful-api on your server. And I noticed a bug from my code, and am debugging it. Will tell you once the it is dealt with.

**Comment by Eggham** [comment]
The bug has been fixed. You may update the code by running:
```
cd ~/shadow-shop
docker-compose down
git pull origin master
docker-compose up -d
```

Then you have get the node up running. After that the `State` of the node in Shadow Shop should be `ok`.

**Comment by B451YbUz75Rn** [comment]
Can not use words to express their gratitude to you, has been available at present, really thank you.！！！
-------------------------------------------------------------
Found a small problem with shadow-shop, because small memory database is often paralyzed, resulting in short access to the site failed.   1C   1G RAM

I will try to install VestaCP such a LNMP environment, and once again thank you for your creation and help.

**Comment by B451YbUz75Rn** [comment]
Can not use words to express their gratitude to you, has been available at present, really thank you.

Found a small problem with shadow-shop, because small memory database is often paralyzed, resulting in short access to the site failed.  1C 1G ARM

 I will try to install the VestaCP environment installation and thank you again for your help.

**Comment by Eggham** [comment]
Glad it god fixed.

You mentioned: 

> Found a small problem with shadow-shop, because small memory database is often paralyzed, resulting in short access to the site failed. 1C 1G ARM

Can you share more info on this? My dev environment is also 1 core and 1G, but x86-64.

**Comment by B451YbUz75Rn** [comment]
Shadow-shop server

Provider: Digitalocean
Charge standard: 5$
System: ubuntu18.04
Configuration: Ubuntu 18.04.2 x64
Area: TOR1
-------------------------
Error message :
1. Unable to connect to the database. Appeared 3 times   
No pictures saved

2.nginx 502 appeared 4 times
![01](https://user-images.githubusercontent.com/38288955/55608772-bd674380-57b1-11e9-83ff-ab23f3cfe10e.png)



Not at the same time

Accessing the Shadow-shop background CPU users are in an unstable state with an 80%-90% occupancy rate.

Vesta CP: It has perfect functions: database, DNS, Mail, firewall... There are many functions, and it is an excellent platform for long-term planning. It only takes two lines of code to complete the installation.
![02](https://user-images.githubusercontent.com/38288955/55608794-c8ba6f00-57b1-11e9-88bf-635f8c4b9881.png)


Docker: Easy to install and efficient. For non-developers, it is not conducive to the novice to maintain the site later, once there is a problem, there will be no ability to solve. Thereby reducing the desire to use

If you can use both Vesta CP and Docker, Shadow-shop will be a perfect project.

I installed a Vesta CP to upload the website directory file, which has been accessed normally. There is a problem here on the server. What else do I need to execute?


![03](https://user-images.githubusercontent.com/38288955/55609514-6e221280-57b3-11e9-8c16-b0324e8aec9a.png)

**Comment by B451YbUz75Rn** [comment]
Installed a new 1C 1G ARM Server shadow-shop It runs perfectly, sorry, my fault may be caused by my operation。
