### ISSUE TITLE
Change ecryption method of existed account seems not work?

### ISSUE THREAD

**Issue by DearTanker** [shadowsocks/shadow-shop#7]
It always show aes-256-cfb on the ports.json.

**Comment by Eggham** [comment]
Well observed. This is a tricky bug to be fixed.

I have reproduced the bug, and will get it fixed soon.

Many Thanks

**Comment by Eggham** [comment]
Bug fixed. 
Shadow Shop is able to perform automatic update once a day at a random time. If you want immediate update then run the following commands:
```
cd ~/shadow-shop
docker-compose down
git pull origin master
docker-compose up -d
```
