### ISSUE TITLE
How to install my own SSL cert?

### ISSUE THREAD

**Issue by DearTanker** [shadowsocks/shadow-shop#8]

**Comment by Eggham** [comment]
Interesting question. Shadow Shop generates free Let's Encrypt certificates. It does not support importing an external certificate.

I am just curious why you want to use your own certificate over a Let's Encrypt certificate.

**Comment by DearTanker** [comment]
After installation, did not have Let's Encrypt certificate.

![20190409093359](https://user-images.githubusercontent.com/1122669/55767283-cfdfc680-5aaa-11e9-8b03-418ecbab5337.png)

After all, I have buy my own ssl, it is better that i can use it.

**Comment by Eggham** [comment]
Did you use `Development` mode? You will get a self-signed certificate if you choose `Development` mode. If you want to get Let's Encrypt certificate, then re-run `sudo sh init.sh` and then choose `Production` mode.

**Comment by DearTanker** [comment]
OK good to know, but still want to know is any way that i can use my own ssl?

**Comment by Eggham** [comment]
Not at the moment, unfortunately. And I don't see any value for developing this feature.
