### ISSUE TITLE
How can I back up user information?

### ISSUE THREAD

**Issue by B451YbUz75Rn** [shadowsocks/shadow-shop#9]
How can I back up user information?
In some cases, the front end shadow-shop is paralyzed and you need to reload how to back up the data information.

**Comment by Eggham** [comment]
Database is backup automatically daily. 

There are 3 level of restart:
1. Restart the current docker containers:
   ```
   cd ~/shadow-shop
   docker-compose restart
   ```

2. Shut down the current docker containers and create new containers:
   ```
   cd ~/shadow-shop
   docker-compose down
   docker-compose up -d
   ```

3. Shut down the current docker containers and create new containers from latest backup database:
   ```
   cd ~/shadow-shop
   docker-compose down -v
   docker-compose up -d
   ```
